The ``101-lazy_matrix_mul`` module

============================

Using ``lazy_matrix_mul``
---------------------

>>> lazy_matrix_mul = __import__('101-lazy_matrix_mul').lazy_matrix_mul

>>> print(lazy_matrix_mul([[1, 2], [3, 4]], [[1, 2], [3, 4]]))
[[ 7 10]
 [15 22]]

>>> print(lazy_matrix_mul([[1, 2]], [[3, 4], [5, 6]]))
[[13 16]]

>>> print(lazy_matrix_mul([[1, 2.3], [3.4, 4.2]], [[1.3, 2.3], [3.3, 4.1]]))
[[ 8.89 11.73]
 [18.28 25.04]]

>>> print(lazy_matrix_mul([[1.0, 2.0], [3.0, 4.0]], [[1.0, 2], [3, 4]]))
[[ 7. 10.]
 [15. 22.]]

>>> try:
...	print(lazy_matrix_mul([[1, 3, 2]], [1, 3, 2]))
... except Exception as err:
...	print(err)
[14]

>>> try:
...	print(lazy_matrix_mul([["Holberton", 5]], [[3, 4], [5, 6]]))
... except Exception as err:
... 	print(err)
invalid data type for einsum

>>> try:
...	print(lazy_matrix_mul([[3, 7], [6, 5]], [[1, 2], ["9", 8]]))
... except Exception as err:
... 	print(err)
invalid data type for einsum

>>> try:
...	print(lazy_matrix_mul([[1], [2]], [[3, 4], [5, 6]]))
... except Exception as err:
... 	print(err)
shapes (2,1) and (2,2) not aligned: 1 (dim 1) != 2 (dim 0)

>>> try:
...	print(lazy_matrix_mul([[6], [6, 7]], [[8, 9], [10, 11]]))
... except Exception as err:
... 	print(err)
setting an array element with a sequence.

>>> try:
...	print(lazy_matrix_mul([[1], [2]], [[2, 3, 4], [5, 6]]))
... except Exception as err:
... 	print(err)
setting an array element with a sequence.

>>> try:
...	print(lazy_matrix_mul(None, None))
... except Exception as err:
... 	print(err)
Object arrays are not currently supported

>>> try:
...	print(lazy_matrix_mul([3, 9], None))
... except Exception as err:
... 	print(err)
Object arrays are not currently supported

>>> try:
...	print(lazy_matrix_mul([], []))
... except Exception as err:
... 	print(err)
0.0

>>> try:
...	print(lazy_matrix_mul([None], []))
... except Exception as err:
... 	print(err)
Object arrays are not currently supported

>>> try:
...	print(lazy_matrix_mul([9, 10, 2], []))
... except Exception as err:
... 	print(err)
shapes (3,) and (0,) not aligned: 3 (dim 0) != 0 (dim 0)

>>> try:
...	print(lazy_matrix_mul([1, 2, 3], [None]))
... except Exception as err:
... 	print(err)
Object arrays are not currently supported

>>> try:
...	print(lazy_matrix_mul([[7, 8, 9]], [None]))
... except Exception as err:
... 	print(err)
Object arrays are not currently supported

>>> try:
...	print(lazy_matrix_mul([[1, 2], [3, 4]], [[]]))
... except Exception as err:
... 	print(err)
shapes (2,2) and (1,0) not aligned: 2 (dim 1) != 1 (dim 0)

>>> try:
...	print(lazy_matrix_mul([[1, 2], [3, 4], [3, 4]], [[5, 6, 1], [7, 8, 2]]))
... except Exception as err:
... 	print(err)
[[19 22  5]
 [43 50 11]
 [43 50 11]]

>>> try:
...	print(lazy_matrix_mul([[1, 2, 3]], ))
... except Exception as err:
...	print(err)
lazy_matrix_mul() missing 1 required positional argument: 'm_b'

>>> try:
...	print(lazy_matrix_mul())
... except Exception as err:
...	print(err)
lazy_matrix_mul() missing 2 required positional arguments: 'm_a' and 'm_b'
